# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PixlguU02S9nfD2aq_vYbobIvks9fSco
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# App Title
st.title("🚗 Car Evaluation Classifier using Random Forest 🚗")
st.write("Predict the car condition using Machine Learning based on various features.")

# Made by Swati (Added credit)
st.markdown("👩‍💻 *Made by: Swati*")

# File uploader to allow users to upload their own file
uploaded_file = st.file_uploader("📁 /content/car.csv", type=['csv'])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    # ... (rest of your code to process the dataframe) ...
else:
    st.warning("⚠ Please upload the car.csv file to proceed.")
